<?php /** @var \GeekHub\RegistrationForm\Block\Widget\Telephone $block */ ?>

<div class="field telephone <?= $block->isRequired() ? 'required' : '' ?>">
    <label for="modal_dealer_telephone" class="label">
        <span>
            <?= $block->escapeHtml(__('Phone Number')) ?>
        </span>
    </label>
    <div class="control">
        <?php $_validationClass = $block->escapeHtmlAttr($this->helper(\Magento\Customer\Helper\Address::class)->getAttributeValidationClass('telephone')); ?>
        <input type="text"
               name="telephone"
               id="modal_dealer_telephone"
               value="<?= $block->escapeHtmlAttr($block->getTelephone()) ?>"
               title="<?= $block->escapeHtmlAttr(__('Phone Number')) ?>"
               class="input-text <?= $_validationClass ?: '' ?>"
        >
    </div>
</div>
