<?php /** @var \GeekHub\AskQuestion\Block\Form\AskQuestion $block */ ?>

<form action="<?= $block->escapeUrl($block->getUrl('ask_question/submit')) ?>"
      id="ask_question_form"
      class="review-form"
      data-mage-init='{"submitQuestion": {}}'
      onsubmit="return false"
>
    <fieldset class="fieldset review-fieldset">
        <div class="field required">
            <label class="label" for="ask_question_name"><span><?= $block->escapeHtml(__('Name')) ?></span></label>
            <div class="control">
                <input title="<?= $block->escapeHtml(__('Name')) ?>"
                       type="text"
                       name="name"
                       id="ask_question_name"
                       placeholder="<?= $block->escapeHtml(__('Enter name')) ?>"
                       data-validate="{required:true}"
                >
            </div>
        </div>
        <div class="field required">
            <label class="label" for="ask_question_email"><span><?= $block->escapeHtml(__('Email')) ?></span></label>
            <div class="control">
                <input title="<?= $block->escapeHtml(__('Email')) ?>"
                       type="email"
                       name="email"
                       id="ask_question_email"
                       placeholder="<?= $block->escapeHtml(__('Enter email')) ?>"
                       data-validate="{required:true, 'validate-email':true}"
                >
            </div>
        </div>
        <div class="field required">
            <label class="label"
                   for="ask_question_number"><span><?= $block->escapeHtml(__('Phone number')) ?></span></label>
            <div class="control">
                <input title="<?= $block->escapeHtml(__('Phone number')) ?>"
                       type="tel"
                       minlength="10"
                       name="phone_number"
                       id="ask_question_number"
                       placeholder="<?= $block->escapeHtml(__('+380xxxxxxxxx')) ?>"
                       data-validate="{required:true, 'validate-ua-phone':true}"
                >
            </div>
        </div>
        <div class="field required">
            <label class="label" for="ask_question_textarea">
                <span><?= $block->escapeHtml(__('Question')) ?></span>
            </label>
            <div class="control">
                <textarea title="<?= $block->escapeHtml(__('Question')) ?>"
                          name="question"
                          form="ask_question_form"
                          id="ask_question_textarea"
                          maxlength="127"
                          rows="10"
                          cols="50"
                          placeholder="<?= $block->escapeHtml(__('Enter your question')) ?>"
                          data-validate="{required:true}"
                ></textarea>
            </div>
        </div>
        <div class="actions-toolbar">
            <div class="primary actions-primary">
                <button class="action submit primary"><?= $block->escapeHtml(__('Submit Question')) ?></button>
            </div>
        </div>
    </fieldset>
</form>
