<?php /** @var \GeekHub\RegistrationForm\Block\Form\Register $block */ ?>
<div class="registration-for-dealer-wrapper">
    <p class="non-target"><?= $block->escapeHtml(__('Registration for dealer')) ?></p>
</div>

<div id="header-registration-modal">
    <div id="registration-form-content-wrapper">
    </div>
</div>

<script type="text/x-magento-init">
    {
        ".registration-for-dealer-wrapper": {
            "additionalRegistrationForm": {}
        }
    }

</script>