<?php /** @var \Magento\Framework\View\Element\Template $block */ ?>
<div class="wrapper-for-chat-window"
     id="wrapper-for-chat-window"
     style="transform: translate(200%, 0)"
     data-mage-init='{"arteml_interactiveChat_chatForm": {}}'
>
    <form action="javascript:void(0);"
          id="chat-form"
          class="chat-form"
          method="post"
    >
        <div class="header-chat-form">
            <span class="operator-icon">
                <span class="icon-user"></span>
                <span>operator</span>
            </span>
            <div class="close-btn" id="close-btn">
                <span class="icon-cancel"></span>
            </div>
        </div>
        <div class="wrapper-for-chat-form-fields">
            <fieldset class="fieldset">
                <div class="chat-history" id="chat-history" data-mage-init='{"arteml_interactiveChat_chatMessages": {}}'>
                    <p class="operator-message">i`m operator</p>
                    <p class="user-message">i`am user</p>
                </div>
            </fieldset>
            <fieldset class="fieldset">
                <div class="field required user-text-area">
                    <label class="label"
                           for="chat-message-field"><span><?= $block->escapeHtml(__('Message to administrator')) ?></span></label>
                    <div class="control">
                        <textarea class="chat-messages"
                                  name="message"
                                  id="chat-message-field"
                                  cols="30"
                                  rows="10"
                                  autofocus
                                  maxlength="255"
                                  placeholder="<?= $block->escapeHtmlAttr(__('Input ur message here')) ?>"
                                  data-validate='{"required":true, "minlength":10, "maxlength": 255}'
                        ></textarea>
                    </div>
                </div>
            </fieldset>
        </div>
        <div class="actions-toolbar">
            <div class="primary">
                <input type="hidden" name="hideit" id="hideit" value=""/>
                <button type="submit" title="<?= $block->escapeHtmlAttr(__('Save')) ?>" class="action submit primary">
                    <span><?= $block->escapeHtml(__('Save')) ?></span>
                </button>
            </div>
        </div>
    </form>
</div>