<?php /** @var \Arteml\InteractiveChat\Block\InteractiveChatForm $block */ ?>
<div class="wrapper-for-chat-window"
     id="wrapper-for-chat-window"
     style="transform: translate(200%, 0)"
     data-mage-init='{"arteml_interactiveChat_chatForm": {}}'
>
    <form action="javascript:void(0);"
          id="chat-form"
          class="chat-form"
          method="post"
    >
        <div class="header-chat-form">
            <span class="operator-icon">
                <span class="icon-user"></span>
                <span>operator</span>
            </span>
            <div class="close-btn" id="close-btn">
                <span class="icon-cancel"></span>
            </div>
        </div>
        <div class="wrapper-for-chat-form-fields">
            <fieldset class="fieldset">
                <div class="chat-history" id="chat-history" data-mage-init='{"arteml_interactiveChat_chatMessages": {}}'></div>
            </fieldset>
            <?php if(!$block->isCustomerLoggedIn()): ?>
                <fieldset class="fieldset margin-bottom-10px">
                    <div class="field required customer-answer-wrapper">
                        <label class="label"
                               for="customer-name"><span><?= $block->escapeHtml(__('Enter your name, please')) ?></span></label>
                        <div class="control">
                            <input type="text"
                                   id="customer-name"
                                   name="customer_name"
                                   placeholder="<?= $block->escapeHtmlAttr(__('Enter your name here')) ?>"
                                   data-validate='{"required":true, "minlength":5, "maxlength": 20}'
                            />
                        </div>
                    </div>
                </fieldset>
            <?php endif; ?>
            <fieldset class="fieldset">
                <div class="field required customer-answer-wrapper">
                    <label class="label"
                           for="chat-message-field"><span><?= $block->escapeHtml(__('Message to administrator')) ?></span></label>
                    <div class="control">
                        <textarea class="customer-answer"
                                  name="message"
                                  id="chat-message-field"
                                  cols="30"
                                  rows="10"
                                  autofocus
                                  maxlength="255"
                                  placeholder="<?= $block->escapeHtmlAttr(__('Enter your message here')) ?>"
                                  data-validate='{"required":true, "minlength":5, "maxlength": 255}'
                        ></textarea>
                    </div>
                </div>
            </fieldset>
        </div>
        <div class="actions-toolbar">
            <div class="primary">
                <input type="hidden" name="hideit" id="hideit" value=""/>
                <button type="submit" title="<?= $block->escapeHtmlAttr(__('Save')) ?>" class="action submit primary">
                    <span><?= $block->escapeHtml(__('Send')) ?></span>
                </button>
            </div>
        </div>
    </form>
</div>